### ISSUE TITLE
Escaped character should include backslash("\\") and form feed("\f")

### ISSUE THREAD

**Issue by guangpingmo** [robertluo/Edn.Net#16]
when EString is converted to string literal, escaped character range should include backslash("\\") and form feed("\f").
https://github.com/robertluo/Edn.Net/blob/92dd6499342b87ea422ddd19611ceebe36ab965a/src/Edn.Net/Library.fs#L34-L45

**Comment by robertluo** [comment]
fixed by 61022fdb822348ed266a1bbaf02c75b75aff4fcc
